source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'KhuongCointCalcu' do
use_frameworks!
pod 'Alamofire', '~> 4.7'
pod 'SDWebImage', '~> 4.0'
pod 'AlamofireObjectMapper', '~> 5.0'
pod 'FoldingCell'
pod 'ViewAnimator'
pod 'Tabman', '~> 2.1'
pod 'Pastel'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'NVActivityIndicatorView'
end
target 'CryptoWidget' do
    use_frameworks!
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireObjectMapper', '~> 5.0'
end
